import type { TRPCRouterRecord } from "@trpc/server";
import { protectedProcedure } from "../../trpc";
import { requireActiveOrgMembership } from "../utils/active-org";
import { forSurfaceSchema } from "./schema";
import { buildStarterPrompts, type StarterPrompt } from "./suggest";

/**
 * Suggestions router (F57, #650) — AI-seeded starter prompts for empty states.
 *
 * The single shared backend that feeds the `@rox/ui` `EmptyState` primitive on
 * every surface (chat / drive / tab, web + desktop + mobile). One read-only
 * procedure, `forSurface`, scoped to the caller's active org. It carries no
 * credential/secret data and runs no migration: the persona/workspace context
 * arrives in the input (resolved client-side from F21/F25), and the starters
 * are generated by the pure `buildStarterPrompts` core.
 */
export const suggestionsRouter = {
	forSurface: protectedProcedure
		.input(forSurfaceSchema)
		.query(async ({ ctx, input }): Promise<StarterPrompt[]> => {
			// Org isolation: only members of the active org may seed its empty
			// states. The starters themselves are context-tinted copy, never org
			// data, so nothing sensitive crosses the boundary.
			await requireActiveOrgMembership(ctx);

			return buildStarterPrompts({
				surface: input.surface,
				personaName: input.personaName ?? null,
				workspaceName: input.workspaceName ?? null,
			});
		}),
} satisfies TRPCRouterRecord;
