import {
	DEFAULT_SETTINGS_EDITOR_FONT_FAMILY,
	DEFAULT_SETTINGS_EDITOR_FONT_SIZE,
} from "@rox/local-db";

export const DEFAULT_CODE_EDITOR_FONT_FAMILY =
	DEFAULT_SETTINGS_EDITOR_FONT_FAMILY;
export const DEFAULT_CODE_EDITOR_FONT_SIZE = DEFAULT_SETTINGS_EDITOR_FONT_SIZE;
